---
- name: remove old self-signed cert for regen
  file:
    dest: "{{ keystone_ssl_cert }}"
    state: absent
  when: keystone_ssl_self_signed_regen | bool

- name: create self-signed ssl certificate
  command: >
    openssl req -new -nodes -sha256 -x509 -subj 
    "{{ keystone_ssl_self_signed_subject }}"
    -days 3650
    -keyout "{{ keystone_ssl_key }}"
    -out "{{ keystone_ssl_cert }}"
    -extensions v3_ca
    creates="{{ keystone_ssl_cert }}"
  notify: Restart Apache

- name: ensure keystone user owns the self-signed key and certificate
  file:
    path: "{{ item }}"
    owner: "{{ keystone_system_user_name }}"
    group: "{{ keystone_system_user_group }}"
    mode: 0640
  with_items:
    - "{{ keystone_ssl_cert }}"
    - "{{ keystone_ssl_key }}"
  notify: Restart Apache