---
- name: place user provides ssl cert
  copy:
    src: "{{ keystone_ssl_user_cert }}"
    dest: "{{ keystone_ssl_cert }}"
    owner: "root"
    group: "root"
    mode: 0640
  notify: Restart Apache

- name: place user provide ssl private key 
  copy:
    src: "{{ keystone_ssl_key }}"
    dest: "{{ keystone_ssl_key }}"
    owner: "root"
    group: "root"
    mode: 0640
  notify: Restart Apache