---
- name: Install and Configure Keystone
  hosts: keystone_all
  pre_tasks:
    - name: Create DB for service
      mysql_db:
        login_user: root
        login_host: localhost
        login_password: "{{ mariadb_root_password }}"
        name: "{{ keystone_database_name }}"
        state: present
      when: inventory_hostname == groups['keystone_all'][0]
      delegate_to: "{{ groups['db_all'][0] }}"
      
    - name: Grant access to keystone DB
      mysql_user:
        login_user: root
        login_host: localhost
        login_password: "{{ mariadb_root_password }}"
        name: "{{ keystone_database_user }}"
        password: "{{ keystone_mysql_password }}"
        host: "{{ item }}"
        state: present
        priv: "{{ keystone_database_name }}.*:ALL"
      with_items:
        - "localhost"
        - "%"
      when: inventory_hostname == groups['keystone_all'][0]
      delegate_to: "{{ groups['db_all'][0] }}"
  roles:
    - os_keystone