---
- name: restart cinder services on controller node(s)
  service:
    name: "{{ item }}"
    state: restarted
  register: glance_api_restart
  until: glance_api_restart|success
  retries: 5
  delay: 2
  with_items:
    - cinder-scheduler
  when: inventory_hostname in groups['cinder_api']

- name: restart cinder services on storage node(s)
  service:
    name: "{{ item }}"
    state: restarted
  register: glance_api_restart
  until: glance_api_restart|success
  retries: 5
  delay: 2
  with_items:
    - cinder-volume
    - tgt
  when: inventory_hostname in groups['cinder_volume']

- name: Restart Apache
  service:
    name: "apache2"
    state: "restarted"
    pattern: "apache2"
  register: apache_restart
  until: apache_restart|success
  retries: 5
  delay: 2
  when: inventory_hostname in groups['cinder_api']