---
- name: Install glance apt packages
  apt:
    name: "{{ item }}"
    state: latest
  register: packages_install
  until: packages_install|success
  retries: 5
  delay: 2
  with_items: "{{ glance_apt_packages }}"