---
- name: Create Identity user for Image Service
  keystone:
    command: "ensure_user"
    user_name: "{{ glance_service_user }}"
    password: "{{ glance_identity_password }}"
    domain_name: "{{ glance_service_user_domain }}"
    login_user: "{{ os_admin_user }}"
    login_user_domain_name: "{{ os_admin_user_domain }}"
    login_password: "{{ os_admin_password }}"
    login_project_name: "{{ os_admin_project }}"
    login_project_domain_name: "{{ os_admin_project_domain }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_ssl_insecure }}"
  no_log: True

- name: create user-role mapping
  keystone:
    command: "ensure_user_role"
    user_name: "{{ glance_service_user }}"
    project_name: "{{ glance_service_project }}"
    role_name: "admin"
    login_user: "{{ os_admin_user }}"
    login_user_domain_name: "{{ os_admin_user_domain }}"
    login_password: "{{ os_admin_password }}"
    login_project_name: "{{ os_admin_project }}"
    login_project_domain_name: "{{ os_admin_project_domain }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_ssl_insecure }}"

- name: create image service 
  keystone:
    command: "ensure_service"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    description: "{{ glance_service_description }}"
    login_user: "{{ os_admin_user }}"
    login_user_domain_name: "{{ os_admin_user_domain }}"
    login_password: "{{ os_admin_password }}"
    login_project_name: "{{ os_admin_project }}"
    login_project_domain_name: "{{ os_admin_project_domain }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_ssl_insecure }}"

- name: create image service's endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "{{ glance_service_region }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    endpoint_list: 
      - url: "{{ glance_service_url }}"
        interface: "public"
      - url: "{{ glance_service_url }}"
        interface: "admin"
      - url: "{{ glance_service_url }}"
        interface: "internal"
    login_user: "{{ os_admin_user }}"
    login_user_domain_name: "{{ os_admin_user_domain }}"
    login_password: "{{ os_admin_password }}"
    login_project_name: "{{ os_admin_project }}"
    login_project_domain_name: "{{ os_admin_project_domain }}"
    endpoint: "{{ keystone_service_adminurl }}"
    insecure: "{{ keystone_ssl_insecure }}"
