---
- name: ensure glance ssl dir exists
  file:
    path: "{{ glance_ssl_dir }}"
    state: "directory"
    owner: "{{ glance_default_system_username }}"
    group: "{{ glance_default_system_group }}"

- name: remove old self-signed cert for regen
  file:
    path: "{{ item }}"
    state: absent
  when: glance_ssl_self_signed_regen | bool
  with_items:
    - "{{ glance_ssl_cert }}"
    - "{{ glance_ssl_key }}"

- name: create self-signed ssl certificate
  command: >
    openssl req -new -nodes -sha256 -x509 -subj 
    "{{ glance_ssl_self_signed_subject }}"
    -days 3650
    -keyout "{{ glance_ssl_key }}"
    -out "{{ glance_ssl_cert }}"
    -extensions v3_ca
    creates="{{ glance_ssl_cert }}"
  notify:
    - Restart glance-api
    - Restart glance-registry

- name: ensure glance user owns the self-signed key and certificate
  file:
    path: "{{ item }}"
    owner: "{{ glance_default_system_username }}"
    group: "{{ glance_default_system_group }}"
    mode: 0640
  with_items:
    - "{{ glance_ssl_cert }}"
    - "{{ glance_ssl_key }}"
  notify:
    - Restart glance-api
    - Restart glance-registry