---
- include: infra_ntp_apt_install.yml
  when: ansible_pkg_mgr == "apt"

- name: Place `chrony` config
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
  notify:
    - restart ntp server