---

- include: infra_message_queue_apt_install.yml
  when: ansible_pkg_mgr == "apt"

- name: create user for openstack services
  rabbitmq_user:
    user: "{{ rabbitmq_auth_user }}"
    password: "{{ rabbitmq_auth_password }}"
    vhost: "/"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present