---
- include: nova_configure.yml

- include: nova_db_setup.yml
  when: inventory_hostname == groups['nova_api'][0]

- include: nova_service_setup.yml
  when: inventory_hostname == groups['nova_api'][0]
  
- meta: flush_handlers