---
- name: ensure cinder ssl dir exists
  file:
    path: "{{ cinder_ssl_dir }}"
    state: "directory"
    owner: "{{ cinder_system_user }}"
    group: "{{ cinder_system_group }}"

- name: remove old self-signed cert for regen
  file:
    path: "{{ item }}"
    state: absent
  when: cinder_ssl_self_signed_regen | bool
  with_items:
    - "{{ cinder_ssl_cert }}"
    - "{{ cinder_ssl_key }}"

- name: create self-signed ssl certificate
  command: >
    openssl req -new -nodes -sha256 -x509 -subj 
    "{{ cinder_ssl_self_signed_subject }}"
    -days 3650
    -keyout "{{ cinder_ssl_key }}"
    -out "{{ cinder_ssl_cert }}"
    -extensions v3_ca
    creates="{{ cinder_ssl_cert }}"
  notify:
    - Restart Apache

- name: ensure cinder user owns the self-signed key and certificate
  file:
    path: "{{ item }}"
    owner: "{{ cinder_system_user }}"
    group: "{{ cinder_system_group }}"
    mode: 0640
  with_items:
    - "{{ cinder_ssl_cert }}"
    - "{{ cinder_ssl_key }}"
  notify:
    - Restart Apache